<?php

// Estructura de datos con las clases por carrera y año.
return [
    'Administración de Empresas' => [
        'Primer Año' => [
            ['nombre' => 'Fundamentos de Administración', 'grupos' => ['1', '2']],
            ['nombre' => 'Contabilidad I', 'grupos' => ['1', '2']],
            ['nombre' => 'Matemática I', 'grupos' => ['1', '2']],
            ['nombre' => 'Comunicación Oral y Escrita', 'grupos' => ['1', '2']],
            ['nombre' => 'Sociología', 'grupos' => ['1', '2']],
            ['nombre' => 'Microeconomía', 'grupos' => ['1', '2']],
            ['nombre' => 'Contabilidad II', 'grupos' => ['1', '2']],
            ['nombre' => 'Estadística I', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Administración de RRHH', 'grupos' => ['1', '2']],
            ['nombre' => 'Macroeconomía', 'grupos' => ['1', '2']],
            ['nombre' => 'Estadística II', 'grupos' => ['1', '2']],
            ['nombre' => 'Matemática Financiera', 'grupos' => ['1', '2']],
            ['nombre' => 'Contabilidad de Costos', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Mercantil', 'grupos' => ['1', '2']],
            ['nombre' => 'Mercadotecnia I', 'grupos' => ['1', '2']],
            ['nombre' => 'Presupuestos', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Administración Financiera I', 'grupos' => ['1', '2']],
            ['nombre' => 'Mercadotecnia II', 'grupos' => ['1', '2']],
            ['nombre' => 'Administración de Operaciones I', 'grupos' => ['1', '2']],
            ['nombre' => 'Organización y Métodos', 'grupos' => ['1', '2']],
            ['nombre' => 'Administración Financiera II', 'grupos' => ['1', '2']],
            ['nombre' => 'Investigación de Mercados', 'grupos' => ['1', '2']],
            ['nombre' => 'Administración de Operaciones II', 'grupos' => ['1', '2']],
            ['nombre' => 'Formulación y Evaluación de Proyectos', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Administración de Ventas', 'grupos' => ['1', '2']],
            ['nombre' => 'Gerencia Estratégica', 'grupos' => ['1', '2']],
            ['nombre' => 'Comercio Electrónico', 'grupos' => ['1', '2']],
            ['nombre' => 'Simulación de Negocios', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Laboral', 'grupos' => ['1', '2']],
            ['nombre' => 'Logística y Distribución', 'grupos' => ['1', '2']],
            ['nombre' => 'Calidad Total', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Tesis', 'grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            ['nombre' => 'Prácticas Profesionales', 'grupos' => ['1', '2']],
            ['nombre' => 'Proyecto de Titulación', 'grupos' => ['1', '2']],
        ],
    ],
    'Contabilidad y Finanzas' => [
        'Primer Año' => [
            ['nombre' => 'Fundamentos de Contabilidad', 'grupos' => ['1', '2']],
            ['nombre' => 'Matemática I', 'grupos' => ['1', '2']],
            ['nombre' => 'Administración I', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Constitucional', 'grupos' => ['1', '2']],
            ['nombre' => 'Contabilidad II', 'grupos' => ['1', '2']],
            ['nombre' => 'Microeconomía', 'grupos' => ['1', '2']],
            ['nombre' => 'Estadística I', 'grupos' => ['1', '2']],
            ['nombre' => 'Informática Aplicada', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Contabilidad de Costos I', 'grupos' => ['1', '2']],
            ['nombre' => 'Macroeconomía', 'grupos' => ['1', '2']],
            ['nombre' => 'Matemática Financiera', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Mercantil', 'grupos' => ['1', '2']],
            ['nombre' => 'Contabilidad de Sociedades', 'grupos' => ['1', '2']],
            ['nombre' => 'Finanzas I', 'grupos' => ['1', '2']],
            ['nombre' => 'Tributación I', 'grupos' => ['1', '2']],
            ['nombre' => 'Mercados Financieros', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Auditoría I', 'grupos' => ['1', '2']],
            ['nombre' => 'Finanzas II', 'grupos' => ['1', '2']],
            ['nombre' => 'Tributación II', 'grupos' => ['1', '2']],
            ['nombre' => 'Contabilidad de Costos II', 'grupos' => ['1', '2']],
            ['nombre' => 'Auditoría II', 'grupos' => ['1', '2']],
            ['nombre' => 'Análisis de Estados Financieros', 'grupos' => ['1', '2']],
            ['nombre' => 'Formulación de Proyectos', 'grupos' => ['1', '2']],
            ['nombre' => 'Normas Internacionales (NIIF)', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Auditoría III', 'grupos' => ['1', '2']],
            ['nombre' => 'Finanzas Corporativas', 'grupos' => ['1', '2']],
            ['nombre' => 'Contabilidad Gubernamental', 'grupos' => ['1', '2']],
            ['nombre' => 'Auditoría de Sistemas', 'grupos' => ['1', '2']],
            ['nombre' => 'Contabilidad Avanzada', 'grupos' => ['1', '2']],
            ['nombre' => 'Consultoría Financiera', 'grupos' => ['1', '2']],
            ['nombre' => 'Ética Profesional', 'grupos' => ['1', '2']],
            ['nombre' => 'Seminario de Tesis', 'grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            ['nombre' => 'Prácticas Profesionales', 'grupos' => ['1', '2']],
            ['nombre' => 'Examen de Grado', 'grupos' => ['1', '2']],
        ],
    ],
    'Economía Empresarial' => [
        'Primer Año' => [
            ['nombre' => 'Principios de Economía', 'grupos' => ['1', '2']],
            ['nombre' => 'Matemática Básica', 'grupos' => ['1', '2']],
            ['nombre' => 'Contabilidad I', 'grupos' => ['1', '2']],
            ['nombre' => 'Introducción a las Ciencias Administrativas', 'grupos' => ['1', '2']],
            ['nombre' => 'Microeconomía I', 'grupos' => ['1', '2']],
            ['nombre' => 'Cálculo Aplicado I', 'grupos' => ['1', '2']],
            ['nombre' => 'Contabilidad II', 'grupos' => ['1', '2']],
            ['nombre' => 'Competencias para Emprender', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Microeconomía II', 'grupos' => ['1', '2']],
            ['nombre' => 'Cálculo Aplicado II', 'grupos' => ['1', '2']],
            ['nombre' => 'Estadística I', 'grupos' => ['1', '2']],
            ['nombre' => 'Macroeconomía I', 'grupos' => ['1', '2']],
            ['nombre' => 'Pensamiento Económico', 'grupos' => ['1', '2']],
            ['nombre' => 'Matemática Financiera', 'grupos' => ['1', '2']],
            ['nombre' => 'Estadística II', 'grupos' => ['1', '2']],
            ['nombre' => 'Macroeconomía II', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Análisis de los Estados Financieros', 'grupos' => ['1', '2']],
            ['nombre' => 'Investigación de Operaciones', 'grupos' => ['1', '2']],
            ['nombre' => 'Finanzas I', 'grupos' => ['1', '2']],
            ['nombre' => 'Macroeconomía III', 'grupos' => ['1', '2']],
            ['nombre' => 'Mercadeo', 'grupos' => ['1', '2']],
            ['nombre' => 'Teoría de Juegos', 'grupos' => ['1', '2']],
            ['nombre' => 'Finanzas II', 'grupos' => ['1', '2']],
            ['nombre' => 'Econometría I', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Economía Internacional', 'grupos' => ['1', '2']],
            ['nombre' => 'Econometría II', 'grupos' => ['1', '2']],
            ['nombre' => 'Evaluación de Proyectos de Inversión', 'grupos' => ['1', '2']],
            ['nombre' => 'Historia Económica', 'grupos' => ['1', '2']],
            ['nombre' => 'Política Económica', 'grupos' => ['1', '2']],
            ['nombre' => 'Economía del Sector Público', 'grupos' => ['1', '2']],
            ['nombre' => 'Seminario de Tópicos Económicos', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Investigación', 'grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            ['nombre' => 'Prácticas de Especialización', 'grupos' => ['1', '2']],
            ['nombre' => 'Tesis de Grado', 'grupos' => ['1', '2']],
        ],
    ],
    'Negocios Internacionales' => [
        'Primer Año' => [
            ['nombre' => 'Administración Global', 'grupos' => ['1', '2']],
            ['nombre' => 'Contabilidad Financiera', 'grupos' => ['1', '2']],
            ['nombre' => 'Economía Global', 'grupos' => ['1', '2']],
            ['nombre' => 'Comunicación Intercultural', 'grupos' => ['1', '2']],
            ['nombre' => 'Marketing Internacional', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Internacional Público', 'grupos' => ['1', '2']],
            ['nombre' => 'Finanzas Globales', 'grupos' => ['1', '2']],
            ['nombre' => 'Estadística para Negocios', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Logística y Cadena de Suministro', 'grupos' => ['1', '2']],
            ['nombre' => 'Investigación de Mercados Globales', 'grupos' => ['1', '2']],
            ['nombre' => 'Tratados y Acuerdos Comerciales', 'grupos' => ['1', '2']],
            ['nombre' => 'Gestión de RRHH Global', 'grupos' => ['1', '2']],
            ['nombre' => 'Estrategia de Negocios Internacionales', 'grupos' => ['1', '2']],
            ['nombre' => 'Cultura y Ética en los Negocios', 'grupos' => ['1', '2']],
            ['nombre' => 'Operaciones de Importación y Exportación', 'grupos' => ['1', '2']],
            ['nombre' => 'Análisis de Riesgo País', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Geopolítica y Negocios', 'grupos' => ['1', '2']],
            ['nombre' => 'Marketing Digital Global', 'grupos' => ['1', '2']],
            ['nombre' => 'Contratos Internacionales', 'grupos' => ['1', '2']],
            ['nombre' => 'Simulación de Negocios Globales', 'grupos' => ['1', '2']],
            ['nombre' => 'Gestión de Proyectos Internacionales', 'grupos' => ['1', '2']],
            ['nombre' => 'Finanzas Corporativas Internacionales', 'grupos' => ['1', '2']],
            ['nombre' => 'Emprendimiento Global', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Graduación I', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Prácticas Profesionales', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Graduación II', 'grupos' => ['1', '2']],
        ],
    ],
    'Derecho' => [
        'Primer Año' => [
            ['nombre' => 'Introducción al Estudio del Derecho', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Romano', 'grupos' => ['1', '2']],
            ['nombre' => 'Teoría del Estado', 'grupos' => ['1', '2']],
            ['nombre' => 'Sociología Jurídica', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho de Personas y Familia', 'grupos' => ['1', '2']],
            ['nombre' => 'Teoría General del Proceso', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Constitucional I', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Derecho de Bienes', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho de Obligaciones', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Penal I', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Constitucional II', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho de Sucesiones', 'grupos' => ['1', '2']],
            ['nombre' => 'Contratos Civiles', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Penal II', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Administrativo I', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Derecho Procesal Civil I', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Mercantil I', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Laboral', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Administrativo II', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Procesal Civil II', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Mercantil II', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Procesal Penal', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Tributario', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Derecho Notarial y Registral I', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Internacional Público', 'grupos' => ['1', '2']],
            ['nombre' => 'Medicina Forense', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Ambiental', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Notarial y Registral II', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Internacional Privado', 'grupos' => ['1', '2']],
            ['nombre' => 'Criminología', 'grupos' => ['1', '2']],
            ['nombre' => 'Métodos Alternos de Resolución de Conflictos', 'grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            ['nombre' => 'Prácticas Penales y Civiles', 'grupos' => ['1', '2']],
            ['nombre' => 'Filosofía del Derecho', 'grupos' => ['1', '2']],
            ['nombre' => 'Técnicas de Litigación Oral', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Tesis', 'grupos' => ['1', '2']],
            ['nombre' => 'Prácticas de Familia, Laboral y Administrativo', 'grupos' => ['1', '2']],
            ['nombre' => 'Deontología Jurídica', 'grupos' => ['1', '2']],
        ],
    ],
    'Diplomacia y Relaciones Internacionales' => [
        'Primer Año' => [
            ['nombre' => 'Introducción a las Relaciones Internacionales', 'grupos' => ['1', '2']],
            ['nombre' => 'Historia Universal', 'grupos' => ['1', '2']],
            ['nombre' => 'Teoría de Relaciones Internacionales I', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Constitucional', 'grupos' => ['1', '2']],
            ['nombre' => 'Introducción al Estudio del Derecho', 'grupos' => ['1', '2']],
            ['nombre' => 'Geopolítica', 'grupos' => ['1', '2']],
            ['nombre' => 'Técnicas de Redacción', 'grupos' => ['1', '2']],
            ['nombre' => 'Historia de Nicaragua', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Teoría de Relaciones Internacionales II', 'grupos' => ['1', '2']],
            ['nombre' => 'Economía Internacional', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Internacional Público', 'grupos' => ['1', '2']],
            ['nombre' => 'Organismos Internacionales I', 'grupos' => ['1', '2']],
            ['nombre' => 'Política Exterior I', 'grupos' => ['1', '2']],
            ['nombre' => 'Protocolo y Ceremonial Diplomático', 'grupos' => ['1', '2']],
            ['nombre' => 'Análisis de Política Internacional', 'grupos' => ['1', '2']],
            ['nombre' => 'Resolución de Conflictos', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Cooperación Internacional', 'grupos' => ['1', '2']],
            ['nombre' => 'Derechos Humanos', 'grupos' => ['1', '2']],
            ['nombre' => 'Política Exterior de Nicaragua', 'grupos' => ['1', '2']],
            ['nombre' => 'Organismos Internacionales II', 'grupos' => ['1', '2']],
            ['nombre' => 'Integración Regional', 'grupos' => ['1', '2']],
            ['nombre' => 'Seguridad Internacional', 'grupos' => ['1', '2']],
            ['nombre' => 'Negociación y Mediación', 'grupos' => ['1', '2']],
            ['nombre' => 'Opinión Pública Internacional', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Derecho Diplomático y Consular', 'grupos' => ['1', '2']],
            ['nombre' => 'Análisis de Coyuntura', 'grupos' => ['1', '2']],
            ['nombre' => 'Política Exterior de EE.UU.', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Investigación Diplomática', 'grupos' => ['1', '2']],
            ['nombre' => 'Prácticas Profesionales', 'grupos' => ['1', '2']],
            ['nombre' => 'Seminario de Graduación', 'grupos' => ['1', '2']],
        ],
    ],
    'Medicina' => [
        'Primer Año' => [
            ['nombre' => 'Anatomía Humana I', 'grupos' => ['1', '2']],
            ['nombre' => 'Histología y Embriología I', 'grupos' => ['1', '2']],
            ['nombre' => 'Bioquímica', 'grupos' => ['1', '2']],
            ['nombre' => 'Salud Pública I', 'grupos' => ['1', '2']],
            ['nombre' => 'Anatomía Humana II', 'grupos' => ['1', '2']],
            ['nombre' => 'Histología y Embriología II', 'grupos' => ['1', '2']],
            ['nombre' => 'Fisiología Médica I', 'grupos' => ['1', '2']],
            ['nombre' => 'Introducción a la Medicina', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Microbiología Médica', 'grupos' => ['1', '2']],
            ['nombre' => 'Parasitología Médica', 'grupos' => ['1', '2']],
            ['nombre' => 'Fisiología Médica II', 'grupos' => ['1', '2']],
            ['nombre' => 'Patología General', 'grupos' => ['1', '2']],
            ['nombre' => 'Farmacología Médica I', 'grupos' => ['1', '2']],
            ['nombre' => 'Inmunología Médica', 'grupos' => ['1', '2']],
            ['nombre' => 'Semiología Médica I', 'grupos' => ['1', '2']],
            ['nombre' => 'Epidemiología', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Medicina Interna I', 'grupos' => ['1', '2']],
            ['nombre' => 'Cirugía I', 'grupos' => ['1', '2']],
            ['nombre' => 'Ginecología y Obstetricia I', 'grupos' => ['1', '2']],
            ['nombre' => 'Pediatría I', 'grupos' => ['1', '2']],
            ['nombre' => 'Psiquiatría', 'grupos' => ['1', '2']],
            ['nombre' => 'Radiología e Imagen', 'grupos' => ['1', '2']],
            ['nombre' => 'Medicina Legal', 'grupos' => ['1', '2']],
            ['nombre' => 'Farmacología Médica II', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Medicina Interna II', 'grupos' => ['1', '2']],
            ['nombre' => 'Cirugía II', 'grupos' => ['1', '2']],
            ['nombre' => 'Ginecología y Obstetricia II', 'grupos' => ['1', '2']],
            ['nombre' => 'Pediatría II', 'grupos' => ['1', '2']],
            ['nombre' => 'Dermatología', 'grupos' => ['1', '2']],
            ['nombre' => 'Oftalmología', 'grupos' => ['1', '2']],
            ['nombre' => 'Otorrinolaringología', 'grupos' => ['1', '2']],
            ['nombre' => 'Urología', 'grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            ['nombre' => 'Internado Rotatorio en Medicina Interna', 'grupos' => ['1', '2']],
            ['nombre' => 'Internado Rotatorio en Cirugía', 'grupos' => ['1', '2']],
            ['nombre' => 'Internado Rotatorio en Pediatría', 'grupos' => ['1', '2']],
            ['nombre' => 'Internado Rotatorio en Ginecología y Obstetricia', 'grupos' => ['1', '2']],
        ],
    ],
    'Psicología' => [
        'Primer Año' => [
            ['nombre' => 'Historia de la Psicología', 'grupos' => ['1', '2']],
            ['nombre' => 'Procesos Psicológicos I', 'grupos' => ['1', '2']],
            ['nombre' => 'Bases Biológicas del Comportamiento', 'grupos' => ['1', '2']],
            ['nombre' => 'Estadística Descriptiva', 'grupos' => ['1', '2']],
            ['nombre' => 'Procesos Psicológicos II', 'grupos' => ['1', '2']],
            ['nombre' => 'Psicología del Desarrollo I', 'grupos' => ['1', '2']],
            ['nombre' => 'Teorías de la Personalidad', 'grupos' => ['1', '2']],
            ['nombre' => 'Psicometría', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Psicología Social', 'grupos' => ['1', '2']],
            ['nombre' => 'Psicopatología I', 'grupos' => ['1', '2']],
            ['nombre' => 'Psicología del Desarrollo II', 'grupos' => ['1', '2']],
            ['nombre' => 'Neuropsicología', 'grupos' => ['1', '2']],
            ['nombre' => 'Psicopatología II', 'grupos' => ['1', '2']],
            ['nombre' => 'Psicología Educativa', 'grupos' => ['1', '2']],
            ['nombre' => 'Evaluación Psicológica I', 'grupos' => ['1', '2']],
            ['nombre' => 'Psicología Organizacional', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Psicología Clínica I', 'grupos' => ['1', '2']],
            ['nombre' => 'Teorías del Aprendizaje', 'grupos' => ['1', '2']],
            ['nombre' => 'Psicología Comunitaria', 'grupos' => ['1', '2']],
            ['nombre' => 'Diseños de Investigación', 'grupos' => ['1', '2']],
            ['nombre' => 'Psicología Clínica II', 'grupos' => ['1', '2']],
            ['nombre' => 'Técnicas de Entrevista', 'grupos' => ['1', '2']],
            ['nombre' => 'Evaluación Psicológica II', 'grupos' => ['1', '2']],
            ['nombre' => 'Psicofarmacología', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Psicoterapia I (Psicoanálisis)', 'grupos' => ['1', '2']],
            ['nombre' => 'Orientación Vocacional y Profesional', 'grupos' => ['1', '2']],
            ['nombre' => 'Psicología de la Salud', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Tesis I', 'grupos' => ['1', '2']],
            ['nombre' => 'Psicoterapia II (Cognitivo-Conductual)', 'grupos' => ['1', '2']],
            ['nombre' => 'Psicología Forense', 'grupos' => ['1', '2']],
            ['nombre' => 'Intervención en Crisis', 'grupos' => ['1', '2']],
            ['nombre' => 'Ética Profesional', 'grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            ['nombre' => 'Prácticas Profesionales Supervisadas', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Tesis II', 'grupos' => ['1', '2']],
            ['nombre' => 'Examen de Grado', 'grupos' => ['1', '2']],
        ],
    ],
    'Nutrición' => [
        'Primer Año' => [
            ['nombre' => 'Química General y Orgánica', 'grupos' => ['1', '2']],
            ['nombre' => 'Biología Celular', 'grupos' => ['1', '2']],
            ['nombre' => 'Anatomía Humana', 'grupos' => ['1', '2']],
            ['nombre' => 'Fundamentos de Nutrición', 'grupos' => ['1', '2']],
            ['nombre' => 'Bioquímica de la Nutrición', 'grupos' => ['1', '2']],
            ['nombre' => 'Fisiología Humana', 'grupos' => ['1', '2']],
            ['nombre' => 'Microbiología de Alimentos', 'grupos' => ['1', '2']],
            ['nombre' => 'Evaluación del Estado Nutricional', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Nutrición en el Ciclo de Vida', 'grupos' => ['1', '2']],
            ['nombre' => 'Tecnología de Alimentos', 'grupos' => ['1', '2']],
            ['nombre' => 'Dietética', 'grupos' => ['1', '2']],
            ['nombre' => 'Salud Pública y Epidemiología', 'grupos' => ['1', '2']],
            ['nombre' => 'Fisiopatología', 'grupos' => ['1', '2']],
            ['nombre' => 'Nutrición Clínica I', 'grupos' => ['1', '2']],
            ['nombre' => 'Bioestadística', 'grupos' => ['1', '2']],
            ['nombre' => 'Educación Nutricional', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Nutrición Clínica II', 'grupos' => ['1', '2']],
            ['nombre' => 'Bioquímica Clínica', 'grupos' => ['1', '2']],
            ['nombre' => 'Soporte Nutricional', 'grupos' => ['1', '2']],
            ['nombre' => 'Psicología de la Alimentación', 'grupos' => ['1', '2']],
            ['nombre' => 'Nutrición Deportiva', 'grupos' => ['1', '2']],
            ['nombre' => 'Gestión de Servicios de Alimentación', 'grupos' => ['1', '2']],
            ['nombre' => 'Investigación en Nutrición', 'grupos' => ['1', '2']],
            ['nombre' => 'Farmacología en Nutrición', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Prácticas Comunitarias', 'grupos' => ['1', '2']],
            ['nombre' => 'Prácticas Clínicas', 'grupos' => ['1', '2']],
            ['nombre' => 'Seminario de Tesis', 'grupos' => ['1', '2']],
        ],
    ],
    'Odontología' => [
        'Primer Año' => [
            ['nombre' => 'Anatomía Humana y de Cabeza y Cuello', 'grupos' => ['1', '2']],
            ['nombre' => 'Histología y Embriología General y Dental', 'grupos' => ['1', '2']],
            ['nombre' => 'Bioquímica', 'grupos' => ['1', '2']],
            ['nombre' => 'Materiales Dentales I', 'grupos' => ['1', '2']],
            ['nombre' => 'Fisiología General y Oral', 'grupos' => ['1', '2']],
            ['nombre' => 'Microbiología e Inmunología', 'grupos' => ['1', '2']],
            ['nombre' => 'Operatoria Dental I', 'grupos' => ['1', '2']],
            ['nombre' => 'Radiología Oral I', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Patología General y Oral', 'grupos' => ['1', '2']],
            ['nombre' => 'Farmacología', 'grupos' => ['1', '2']],
            ['nombre' => 'Anestesia y Exodoncia I', 'grupos' => ['1', '2']],
            ['nombre' => 'Operatoria Dental II', 'grupos' => ['1', '2']],
            ['nombre' => 'Periodoncia I', 'grupos' => ['1', '2']],
            ['nombre' => 'Prostodoncia Fija y Removible I', 'grupos' => ['1', '2']],
            ['nombre' => 'Endodoncia I', 'grupos' => ['1', '2']],
            ['nombre' => 'Salud Pública Dental', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Clínica de Operatoria Dental I', 'grupos' => ['1', '2']],
            ['nombre' => 'Clínica de Periodoncia I', 'grupos' => ['1', '2']],
            ['nombre' => 'Clínica de Endodoncia I', 'grupos' => ['1', '2']],
            ['nombre' => 'Odontopediatría I', 'grupos' => ['1', '2']],
            ['nombre' => 'Ortodoncia Preventiva e Interceptiva', 'grupos' => ['1', '2']],
            ['nombre' => 'Cirugía Bucal I', 'grupos' => ['1', '2']],
            ['nombre' => 'Medicina Interna para Odontólogos', 'grupos' => ['1', '2']],
            ['nombre' => 'Oclusión', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Clínica Integral del Adulto I', 'grupos' => ['1', '2']],
            ['nombre' => 'Clínica Integral del Niño I', 'grupos' => ['1', '2']],
            ['nombre' => 'Cirugía Bucal II', 'grupos' => ['1', '2']],
            ['nombre' => 'Implantología Oral', 'grupos' => ['1', '2']],
            ['nombre' => 'Odontología Legal y Forense', 'grupos' => ['1', '2']],
            ['nombre' => 'Prótesis Total y Parcial', 'grupos' => ['1', '2']],
            ['nombre' => 'Patología Bucal', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Investigación', 'grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            ['nombre' => 'Clínica Integral del Adulto II', 'grupos' => ['1', '2']],
            ['nombre' => 'Clínica Integral del Niño II', 'grupos' => ['1', '2']],
            ['nombre' => 'Pasantías Hospitalarias', 'grupos' => ['1', '2']],
            ['nombre' => 'Administración de Consultorio Dental', 'grupos' => ['1', '2']],
            ['nombre' => 'Tesis de Grado', 'grupos' => ['1', '2']],
        ],
    ],
    'Arquitectura' => [
        'Primer Año' => [
            ['nombre' => 'Geometría Descriptiva', 'grupos' => ['1', '2']],
            ['nombre' => 'Dibujo Arquitectónico I', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Diseño I', 'grupos' => ['1', '2']],
            ['nombre' => 'Matemáticas para Arquitectura', 'grupos' => ['1', '2']],
            ['nombre' => 'Historia del Arte y la Arquitectura I', 'grupos' => ['1', '2']],
            ['nombre' => 'Dibujo Arquitectónico II', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Diseño II', 'grupos' => ['1', '2']],
            ['nombre' => 'Física Aplicada', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Taller de Diseño III', 'grupos' => ['1', '2']],
            ['nombre' => 'Estructuras I', 'grupos' => ['1', '2']],
            ['nombre' => 'Historia de la Arquitectura II', 'grupos' => ['1', '2']],
            ['nombre' => 'Sistemas Constructivos I', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Diseño IV', 'grupos' => ['1', '2']],
            ['nombre' => 'Estructuras II', 'grupos' => ['1', '2']],
            ['nombre' => 'Instalaciones I (Hidrosanitarias)', 'grupos' => ['1', '2']],
            ['nombre' => 'Sistemas Constructivos II', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Taller de Diseño V (Vivienda)', 'grupos' => ['1', '2']],
            ['nombre' => 'Urbanismo I', 'grupos' => ['1', '2']],
            ['nombre' => 'Instalaciones II (Eléctricas y Especiales)', 'grupos' => ['1', '2']],
            ['nombre' => 'Arquitectura Bioclimática', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Diseño VI (Comercial)', 'grupos' => ['1', '2']],
            ['nombre' => 'Urbanismo II', 'grupos' => ['1', '2']],
            ['nombre' => 'Administración de Proyectos de Construcción', 'grupos' => ['1', '2']],
            ['nombre' => 'Presupuestos de Construcción', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Taller de Diseño VII (Institucional)', 'grupos' => ['1', '2']],
            ['nombre' => 'Paisajismo', 'grupos' => ['1', '2']],
            ['nombre' => 'Restauración de Monumentos', 'grupos' => ['1', '2']],
            ['nombre' => 'Diseño Estructural en Acero y Concreto', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Diseño VIII (Urbano)', 'grupos' => ['1', '2']],
            ['nombre' => 'Legislación de la Construcción', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Tesis I', 'grupos' => ['1', '2']],
            ['nombre' => 'Prácticas Profesionales', 'grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            ['nombre' => 'Taller de Tesis II', 'grupos' => ['1', '2']],
            ['nombre' => 'Gestión Inmobiliaria', 'grupos' => ['1', '2']],
            ['nombre' => 'Seminario de Arquitectura Contemporánea', 'grupos' => ['1', '2']],
            ['nombre' => 'Proyecto de Graduación', 'grupos' => ['1', '2']],
        ],
    ],
    'Ingeniería Civil' => [
        'Primer Año' => [
            ['nombre' => 'Cálculo I', 'grupos' => ['1', '2']],
            ['nombre' => 'Física I', 'grupos' => ['1', '2']],
            ['nombre' => 'Química General', 'grupos' => ['1', '2']],
            ['nombre' => 'Dibujo Técnico', 'grupos' => ['1', '2']],
            ['nombre' => 'Introducción a la Ingeniería Civil', 'grupos' => ['1', '2']],
            ['nombre' => 'Cálculo II', 'grupos' => ['1', '2']],
            ['nombre' => 'Física II', 'grupos' => ['1', '2']],
            ['nombre' => 'Estática', 'grupos' => ['1', '2']],
            ['nombre' => 'Programación para Ingenieros', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Cálculo III', 'grupos' => ['1', '2']],
            ['nombre' => 'Dinámica', 'grupos' => ['1', '2']],
            ['nombre' => 'Mecánica de Materiales I', 'grupos' => ['1', '2']],
            ['nombre' => 'Topografía', 'grupos' => ['1', '2']],
            ['nombre' => 'Geología para Ingenieros', 'grupos' => ['1', '2']],
            ['nombre' => 'Ecuaciones Diferenciales', 'grupos' => ['1', '2']],
            ['nombre' => 'Mecánica de Materiales II', 'grupos' => ['1', '2']],
            ['nombre' => 'Mecánica de Fluidos', 'grupos' => ['1', '2']],
            ['nombre' => 'Materiales de Construcción', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Análisis Estructural I', 'grupos' => ['1', '2']],
            ['nombre' => 'Hidrología', 'grupos' => ['1', '2']],
            ['nombre' => 'Mecánica de Suelos I', 'grupos' => ['1', '2']],
            ['nombre' => 'Ingeniería de Tránsito', 'grupos' => ['1', '2']],
            ['nombre' => 'Análisis Estructural II', 'grupos' => ['1', '2']],
            ['nombre' => 'Hidráulica', 'grupos' => ['1', '2']],
            ['nombre' => 'Mecánica de Suelos II', 'grupos' => ['1', '2']],
            ['nombre' => 'Diseño de Pavimentos', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Diseño de Estructuras de Concreto Reforzado I', 'grupos' => ['1', '2']],
            ['nombre' => 'Ingeniería Sanitaria', 'grupos' => ['1', '2']],
            ['nombre' => 'Cimentaciones', 'grupos' => ['1', '2']],
            ['nombre' => 'Ingeniería de Costos y Presupuestos', 'grupos' => ['1', '2']],
            ['nombre' => 'Diseño de Estructuras de Concreto Reforzado II', 'grupos' => ['1', '2']],
            ['nombre' => 'Abastecimiento de Agua Potable', 'grupos' => ['1', '2']],
            ['nombre' => 'Ingeniería de Puentes', 'grupos' => ['1', '2']],
            ['nombre' => 'Administración de la Construcción', 'grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            ['nombre' => 'Diseño de Estructuras de Acero', 'grupos' => ['1', '2']],
            ['nombre' => 'Ingeniería Sísmica', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Diseño Estructural', 'grupos' => ['1', '2']],
            ['nombre' => 'Ética y Práctica Profesional', 'grupos' => ['1', '2']],
            ['nombre' => 'Proyecto de Graduación', 'grupos' => ['1', '2']],
            ['nombre' => 'Prácticas Profesionales', 'grupos' => ['1', '2']],
        ],
    ],
    'Ingeniería Industrial' => [
        'Primer Año' => [
            ['nombre' => 'Cálculo I', 'grupos' => ['1', '2']],
            ['nombre' => 'Física I', 'grupos' => ['1', '2']],
            ['nombre' => 'Química General', 'grupos' => ['1', '2']],
            ['nombre' => 'Dibujo Industrial', 'grupos' => ['1', '2']],
            ['nombre' => 'Introducción a la Ingeniería Industrial', 'grupos' => ['1', '2']],
            ['nombre' => 'Cálculo II', 'grupos' => ['1', '2']],
            ['nombre' => 'Física II', 'grupos' => ['1', '2']],
            ['nombre' => 'Electricidad y Magnetismo', 'grupos' => ['1', '2']],
            ['nombre' => 'Estadística I', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Procesos de Manufactura', 'grupos' => ['1', '2']],
            ['nombre' => 'Ingeniería de Métodos', 'grupos' => ['1', '2']],
            ['nombre' => 'Contabilidad de Costos', 'grupos' => ['1', '2']],
            ['nombre' => 'Investigación de Operaciones I', 'grupos' => ['1', '2']],
            ['nombre' => 'Termodinámica', 'grupos' => ['1', '2']],
            ['nombre' => 'Ingeniería Económica', 'grupos' => ['1', '2']],
            ['nombre' => 'Seguridad e Higiene Industrial', 'grupos' => ['1', '2']],
            ['nombre' => 'Control Estadístico de Calidad', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Investigación de Operaciones II', 'grupos' => ['1', '2']],
            ['nombre' => 'Gestión de la Calidad Total', 'grupos' => ['1', '2']],
            ['nombre' => 'Planeación y Control de la Producción I', 'grupos' => ['1', '2']],
            ['nombre' => 'Diseño de Instalaciones', 'grupos' => ['1', '2']],
            ['nombre' => 'Ergonomía', 'grupos' => ['1', '2']],
            ['nombre' => 'Logística y Cadena de Suministro', 'grupos' => ['1', '2']],
            ['nombre' => 'Planeación y Control de la Producción II', 'grupos' => ['1', '2']],
            ['nombre' => 'Automatización Industrial', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Simulación de Sistemas', 'grupos' => ['1', '2']],
            ['nombre' => 'Formulación y Evaluación de Proyectos', 'grupos' => ['1', '2']],
            ['nombre' => 'Gestión del Mantenimiento', 'grupos' => ['1', '2']],
            ['nombre' => 'Sistemas Integrados de Gestión (ISO)', 'grupos' => ['1', '2']],
            ['nombre' => 'Ingeniería Financiera', 'grupos' => ['1', '2']],
            ['nombre' => 'Gestión Ambiental', 'grupos' => ['1', '2']],
            ['nombre' => 'Marketing para Ingenieros', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Tesis', 'grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            ['nombre' => 'Prácticas Profesionales', 'grupos' => ['1', '2']],
            ['nombre' => 'Proyecto de Grado', 'grupos' => ['1', '2']],
        ],
    ],
    'Ingeniería en Sistemas de Información' => [
        'Primer Año' => [
            ['nombre' => 'Cálculo I', 'grupos' => ['1', '2']],
            ['nombre' => 'Física I', 'grupos' => ['1', '2']],
            ['nombre' => 'Introducción a la Programación', 'grupos' => ['1', '2']],
            ['nombre' => 'Comunicación Oral y Escrita', 'grupos' => ['1', '2']],
            ['nombre' => 'Cálculo II', 'grupos' => ['1', '2']],
            ['nombre' => 'Física II', 'grupos' => ['1', '2']],
            ['nombre' => 'Programación I', 'grupos' => ['1', '2']],
            ['nombre' => 'Álgebra Lineal', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Cálculo III', 'grupos' => ['1', '2']],
            ['nombre' => 'Programación II', 'grupos' => ['1', '2']],
            ['nombre' => 'Contabilidad de Costos', 'grupos' => ['1', '2']],
            ['nombre' => 'Estructuras Discretas', 'grupos' => ['1', '2']],
            ['nombre' => 'Ecuaciones Diferenciales', 'grupos' => ['1', '2']],
            ['nombre' => 'Programación Orientada a Objetos', 'grupos' => ['1', '2']],
            ['nombre' => 'Base de Datos I', 'grupos' => ['1', '2']],
            ['nombre' => 'Análisis y Diseño de Sistemas', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Probabilidad y Estadística', 'grupos' => ['1', '2']],
            ['nombre' => 'Base de Datos II', 'grupos' => ['1', '2']],
            ['nombre' => 'Sistemas Operativos', 'grupos' => ['1', '2']],
            ['nombre' => 'Redes de Computadoras I', 'grupos' => ['1', '2']],
            ['nombre' => 'Investigación de Operaciones', 'grupos' => ['1', '2']],
            ['nombre' => 'Ingeniería de Software I', 'grupos' => ['1', '2']],
            ['nombre' => 'Redes de Computadoras II', 'grupos' => ['1', '2']],
            ['nombre' => 'Programación Web', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Inteligencia Artificial', 'grupos' => ['1', '2']],
            ['nombre' => 'Seguridad Informática', 'grupos' => ['1', '2']],
            ['nombre' => 'Ingeniería de Software II', 'grupos' => ['1', '2']],
            ['nombre' => 'Redes Avanzadas', 'grupos' => ['1', '2']],
            ['nombre' => 'Sistemas de Información Gerencial', 'grupos' => ['1', '2']],
            ['nombre' => 'Auditoría de Sistemas', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Graduación I', 'grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            ['nombre' => 'Prácticas Profesionales', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Graduación II', 'grupos' => ['1', '2']],
            ['nombre' => 'Computación en la Nube', 'grupos' => ['1', '2']],
            ['nombre' => 'Desarrollo de Aplicaciones Móviles', 'grupos' => ['1', '2']],
        ],
    ],
    'Marketing y Publicidad' => [
        'Primer Año' => [
            ['nombre' => 'Principios de Marketing', 'grupos' => ['1', '2']],
            ['nombre' => 'Comportamiento del Consumidor', 'grupos' => ['1', '2']],
            ['nombre' => 'Comunicación Integrada', 'grupos' => ['1', '2']],
            ['nombre' => 'Diseño Gráfico Publicitario', 'grupos' => ['1', '2']],
            ['nombre' => 'Fundamentos de Economía', 'grupos' => ['1', '2']],
            ['nombre' => 'Fotografía Publicitaria', 'grupos' => ['1', '2']],
            ['nombre' => 'Costos y Presupuestos', 'grupos' => ['1', '2']],
            ['nombre' => 'Investigación de Mercados I', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Estrategia de Marca (Branding)', 'grupos' => ['1', '2']],
            ['nombre' => 'Marketing Digital I', 'grupos' => ['1', '2']],
            ['nombre' => 'Planificación de Medios', 'grupos' => ['1', '2']],
            ['nombre' => 'Redacción Creativa', 'grupos' => ['1', '2']],
            ['nombre' => 'Derecho Publicitario', 'grupos' => ['1', '2']],
            ['nombre' => 'Marketing Digital II (SEO/SEM)', 'grupos' => ['1', '2']],
            ['nombre' => 'Producción Audiovisual', 'grupos' => ['1', '2']],
            ['nombre' => 'Relaciones Públicas', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Gerencia de Producto', 'grupos' => ['1', '2']],
            ['nombre' => 'E-Commerce', 'grupos' => ['1', '2']],
            ['nombre' => 'Psicología Publicitaria', 'grupos' => ['1', '2']],
            ['nombre' => 'Marketing Estratégico', 'grupos' => ['1', '2']],
            ['nombre' => 'Neuromarketing', 'grupos' => ['1', '2']],
            ['nombre' => 'Análisis de Datos (Analytics)', 'grupos' => ['1', '2']],
            ['nombre' => 'Publicidad Exterior y BTL', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Campañas Publicitarias', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Marketing de Servicios', 'grupos' => ['1', '2']],
            ['nombre' => 'Gerencia de Ventas', 'grupos' => ['1', '2']],
            ['nombre' => 'Ética y Responsabilidad Social', 'grupos' => ['1', '2']],
            ['nombre' => 'Seminario de Tesis', 'grupos' => ['1', '2']],
            ['nombre' => 'Prácticas Profesionales', 'grupos' => ['1', '2']],
        ],
    ],
    'Diseño y Comunicación Visual' => [
        'Primer Año' => [
            ['nombre' => 'Fundamentos del Diseño', 'grupos' => ['1', '2']],
            ['nombre' => 'Teoría del Color', 'grupos' => ['1', '2']],
            ['nombre' => 'Dibujo Artístico I', 'grupos' => ['1', '2']],
            ['nombre' => 'Historia del Arte', 'grupos' => ['1', '2']],
            ['nombre' => 'Tipografía I', 'grupos' => ['1', '2']],
            ['nombre' => 'Dibujo Artístico II', 'grupos' => ['1', '2']],
            ['nombre' => 'Fotografía Básica', 'grupos' => ['1', '2']],
            ['nombre' => 'Geometría del Diseño', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Diseño Editorial', 'grupos' => ['1', '2']],
            ['nombre' => 'Ilustración Digital', 'grupos' => ['1', '2']],
            ['nombre' => 'Tipografía II', 'grupos' => ['1', '2']],
            ['nombre' => 'Historia del Diseño Gráfico', 'grupos' => ['1', '2']],
            ['nombre' => 'Diseño de Empaques (Packaging)', 'grupos' => ['1', '2']],
            ['nombre' => 'Modelado 3D', 'grupos' => ['1', '2']],
            ['nombre' => 'Diseño Web I', 'grupos' => ['1', '2']],
            ['nombre' => 'Semiótica Visual', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Diseño de Identidad Corporativa (Branding)', 'grupos' => ['1', '2']],
            ['nombre' => 'Animación 2D', 'grupos' => ['1', '2']],
            ['nombre' => 'Diseño de Interfaz de Usuario (UI)', 'grupos' => ['1', '2']],
            ['nombre' => 'Producción Gráfica', 'grupos' => ['1', '2']],
            ['nombre' => 'Diseño de Experiencia de Usuario (UX)', 'grupos' => ['1', '2']],
            ['nombre' => 'Dirección de Arte', 'grupos' => ['1', '2']],
            ['nombre' => 'Portafolio Profesional I', 'grupos' => ['1', '2']],
            ['nombre' => 'Diseño Web II', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Diseño de Información (Infografía)', 'grupos' => ['1', '2']],
            ['nombre' => 'Motion Graphics', 'grupos' => ['1', '2']],
            ['nombre' => 'Portafolio Profesional II', 'grupos' => ['1', '2']],
            ['nombre' => 'Gestión de Proyectos de Diseño', 'grupos' => ['1', '2']],
            ['nombre' => 'Prácticas Profesionales', 'grupos' => ['1', '2']],
            ['nombre' => 'Proyecto de Tesis', 'grupos' => ['1', '2']],
        ],
    ],
    'Comunicación y Relaciones Públicas' => [
        'Primer Año' => [
            ['nombre' => 'Teoría de la Comunicación', 'grupos' => ['1', '2']],
            ['nombre' => 'Redacción Periodística I', 'grupos' => ['1', '2']],
            ['nombre' => 'Comunicación Oral', 'grupos' => ['1', '2']],
            ['nombre' => 'Historia de los Medios', 'grupos' => ['1', '2']],
            ['nombre' => 'Introducción a las Relaciones Públicas', 'grupos' => ['1', '2']],
            ['nombre' => 'Redacción Periodística II', 'grupos' => ['1', '2']],
            ['nombre' => 'Opinión Pública', 'grupos' => ['1', '2']],
            ['nombre' => 'Fotoperiodismo', 'grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            ['nombre' => 'Comunicación Corporativa', 'grupos' => ['1', '2']],
            ['nombre' => 'Gestión de Crisis', 'grupos' => ['1', '2']],
            ['nombre' => 'Producción Radiofónica', 'grupos' => ['1', '2']],
            ['nombre' => 'Ética y Legislación de Medios', 'grupos' => ['1', '2']],
            ['nombre' => 'Organización de Eventos', 'grupos' => ['1', '2']],
            ['nombre' => 'Comunicación Digital y Redes Sociales', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Televisión', 'grupos' => ['1', '2']],
            ['nombre' => 'Estrategias de Relaciones Públicas', 'grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            ['nombre' => 'Comunicación Política y Lobbying', 'grupos' => ['1', '2']],
            ['nombre' => 'Comunicación Interna', 'grupos' => ['1', '2']],
            ['nombre' => 'Investigación de la Comunicación', 'grupos' => ['1', '2']],
            ['nombre' => 'Producción de Contenidos Digitales', 'grupos' => ['1', '2']],
            ['nombre' => 'Protocolo Empresarial y Social', 'grupos' => ['1', '2']],
            ['nombre' => 'Gestión de la Reputación Online', 'grupos' => ['1', '2']],
            ['nombre' => 'Portavocía', 'grupos' => ['1', '2']],
            ['nombre' => 'Taller de Agencia', 'grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            ['nombre' => 'Comunicación Intercultural', 'grupos' => ['1', '2']],
            ['nombre' => 'Responsabilidad Social Corporativa', 'grupos' => ['1', '2']],
            ['nombre' => 'Seminario de Tesis', 'grupos' => ['1', '2']],
            ['nombre' => 'Prácticas Profesionales', 'grupos' => ['1', '2']],
        ],
    ],
];