<?php

// config/academic.php
// Estructura de datos final, con la clase como llave para una búsqueda eficiente.

return [
    'Administración de Empresas' => [
        'Primer Año' => [
            'Fundamentos de Administración' => ['grupos' => ['1', '2']],
            'Contabilidad I' => ['grupos' => ['1', '2']],
            'Matemática I' => ['grupos' => ['1', '2']],
            'Comunicación Oral y Escrita' => ['grupos' => ['1', '2']],
            'Sociología' => ['grupos' => ['1', '2']],
            'Microeconomía' => ['grupos' => ['1', '2']],
            'Contabilidad II' => ['grupos' => ['1', '2']],
            'Estadística I' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Administración de RRHH' => ['grupos' => ['1', '2']],
            'Macroeconomía' => ['grupos' => ['1', '2']],
            'Estadística II' => ['grupos' => ['1', '2']],
            'Matemática Financiera' => ['grupos' => ['1', '2']],
            'Contabilidad de Costos' => ['grupos' => ['1', '2']],
            'Derecho Mercantil' => ['grupos' => ['1', '2']],
            'Mercadotecnia I' => ['grupos' => ['1', '2']],
            'Presupuestos' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Administración Financiera I' => ['grupos' => ['1', '2']],
            'Mercadotecnia II' => ['grupos' => ['1', '2']],
            'Administración de Operaciones I' => ['grupos' => ['1', '2']],
            'Organización y Métodos' => ['grupos' => ['1', '2']],
            'Administración Financiera II' => ['grupos' => ['1', '2']],
            'Investigación de Mercados' => ['grupos' => ['1', '2']],
            'Administración de Operaciones II' => ['grupos' => ['1', '2']],
            'Formulación y Evaluación de Proyectos' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Administración de Ventas' => ['grupos' => ['1', '2']],
            'Gerencia Estratégica' => ['grupos' => ['1', '2']],
            'Comercio Electrónico' => ['grupos' => ['1', '2']],
            'Simulación de Negocios' => ['grupos' => ['1', '2']],
            'Derecho Laboral' => ['grupos' => ['1', '2']],
            'Logística y Distribución' => ['grupos' => ['1', '2']],
            'Calidad Total' => ['grupos' => ['1', '2']],
            'Taller de Tesis' => ['grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            'Prácticas Profesionales' => ['grupos' => ['1', '2']],
            'Proyecto de Titulación' => ['grupos' => ['1', '2']],
        ],
    ],
    'Contabilidad y Finanzas' => [
        'Primer Año' => [
            'Fundamentos de Contabilidad' => ['grupos' => ['1', '2']],
            'Matemática I' => ['grupos' => ['1', '2']],
            'Administración I' => ['grupos' => ['1', '2']],
            'Derecho Constitucional' => ['grupos' => ['1', '2']],
            'Contabilidad II' => ['grupos' => ['1', '2']],
            'Microeconomía' => ['grupos' => ['1', '2']],
            'Estadística I' => ['grupos' => ['1', '2']],
            'Informática Aplicada' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Contabilidad de Costos I' => ['grupos' => ['1', '2']],
            'Macroeconomía' => ['grupos' => ['1', '2']],
            'Matemática Financiera' => ['grupos' => ['1', '2']],
            'Derecho Mercantil' => ['grupos' => ['1', '2']],
            'Contabilidad de Sociedades' => ['grupos' => ['1', '2']],
            'Finanzas I' => ['grupos' => ['1', '2']],
            'Tributación I' => ['grupos' => ['1', '2']],
            'Mercados Financieros' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Auditoría I' => ['grupos' => ['1', '2']],
            'Finanzas II' => ['grupos' => ['1', '2']],
            'Tributación II' => ['grupos' => ['1', '2']],
            'Contabilidad de Costos II' => ['grupos' => ['1', '2']],
            'Auditoría II' => ['grupos' => ['1', '2']],
            'Análisis de Estados Financieros' => ['grupos' => ['1', '2']],
            'Formulación de Proyectos' => ['grupos' => ['1', '2']],
            'Normas Internacionales (NIIF)' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Auditoría III' => ['grupos' => ['1', '2']],
            'Finanzas Corporativas' => ['grupos' => ['1', '2']],
            'Contabilidad Gubernamental' => ['grupos' => ['1', '2']],
            'Auditoría de Sistemas' => ['grupos' => ['1', '2']],
            'Contabilidad Avanzada' => ['grupos' => ['1', '2']],
            'Consultoría Financiera' => ['grupos' => ['1', '2']],
            'Ética Profesional' => ['grupos' => ['1', '2']],
            'Seminario de Tesis' => ['grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            'Prácticas Profesionales' => ['grupos' => ['1', '2']],
            'Examen de Grado' => ['grupos' => ['1', '2']],
        ],
    ],
    'Economía Empresarial' => [
        'Primer Año' => [
            'Principios de Economía' => ['grupos' => ['1', '2']],
            'Matemática Básica' => ['grupos' => ['1', '2']],
            'Contabilidad I' => ['grupos' => ['1', '2']],
            'Introducción a las Ciencias Administrativas' => ['grupos' => ['1', '2']],
            'Microeconomía I' => ['grupos' => ['1', '2']],
            'Cálculo Aplicado I' => ['grupos' => ['1', '2']],
            'Contabilidad II' => ['grupos' => ['1', '2']],
            'Competencias para Emprender' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Microeconomía II' => ['grupos' => ['1', '2']],
            'Cálculo Aplicado II' => ['grupos' => ['1', '2']],
            'Estadística I' => ['grupos' => ['1', '2']],
            'Macroeconomía I' => ['grupos' => ['1', '2']],
            'Pensamiento Económico' => ['grupos' => ['1', '2']],
            'Matemática Financiera' => ['grupos' => ['1', '2']],
            'Estadística II' => ['grupos' => ['1', '2']],
            'Macroeconomía II' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Análisis de los Estados Financieros' => ['grupos' => ['1', '2']],
            'Investigación de Operaciones' => ['grupos' => ['1', '2']],
            'Finanzas I' => ['grupos' => ['1', '2']],
            'Macroeconomía III' => ['grupos' => ['1', '2']],
            'Mercadeo' => ['grupos' => ['1', '2']],
            'Teoría de Juegos' => ['grupos' => ['1', '2']],
            'Finanzas II' => ['grupos' => ['1', '2']],
            'Econometría I' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Economía Internacional' => ['grupos' => ['1', '2']],
            'Econometría II' => ['grupos' => ['1', '2']],
            'Evaluación de Proyectos de Inversión' => ['grupos' => ['1', '2']],
            'Historia Económica' => ['grupos' => ['1', '2']],
            'Política Económica' => ['grupos' => ['1', '2']],
            'Economía del Sector Público' => ['grupos' => ['1', '2']],
            'Seminario de Tópicos Económicos' => ['grupos' => ['1', '2']],
            'Taller de Investigación' => ['grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            'Prácticas de Especialización' => ['grupos' => ['1', '2']],
            'Tesis de Grado' => ['grupos' => ['1', '2']],
        ],
    ],
    'Negocios Internacionales' => [
        'Primer Año' => [
            'Administración Global' => ['grupos' => ['1', '2']],
            'Contabilidad Financiera' => ['grupos' => ['1', '2']],
            'Economía Global' => ['grupos' => ['1', '2']],
            'Comunicación Intercultural' => ['grupos' => ['1', '2']],
            'Marketing Internacional' => ['grupos' => ['1', '2']],
            'Derecho Internacional Público' => ['grupos' => ['1', '2']],
            'Finanzas Globales' => ['grupos' => ['1', '2']],
            'Estadística para Negocios' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Logística y Cadena de Suministro' => ['grupos' => ['1', '2']],
            'Investigación de Mercados Globales' => ['grupos' => ['1', '2']],
            'Tratados y Acuerdos Comerciales' => ['grupos' => ['1', '2']],
            'Gestión de RRHH Global' => ['grupos' => ['1', '2']],
            'Estrategia de Negocios Internacionales' => ['grupos' => ['1', '2']],
            'Cultura y Ética en los Negocios' => ['grupos' => ['1', '2']],
            'Operaciones de Importación y Exportación' => ['grupos' => ['1', '2']],
            'Análisis de Riesgo País' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Geopolítica y Negocios' => ['grupos' => ['1', '2']],
            'Marketing Digital Global' => ['grupos' => ['1', '2']],
            'Contratos Internacionales' => ['grupos' => ['1', '2']],
            'Simulación de Negocios Globales' => ['grupos' => ['1', '2']],
            'Gestión de Proyectos Internacionales' => ['grupos' => ['1', '2']],
            'Finanzas Corporativas Internacionales' => ['grupos' => ['1', '2']],
            'Emprendimiento Global' => ['grupos' => ['1', '2']],
            'Taller de Graduación I' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Prácticas Profesionales' => ['grupos' => ['1', '2']],
            'Taller de Graduación II' => ['grupos' => ['1', '2']],
        ],
    ],
    'Derecho' => [
        'Primer Año' => [
            'Introducción al Estudio del Derecho' => ['grupos' => ['1', '2']],
            'Derecho Romano' => ['grupos' => ['1', '2']],
            'Teoría del Estado' => ['grupos' => ['1', '2']],
            'Sociología Jurídica' => ['grupos' => ['1', '2']],
            'Derecho de Personas y Familia' => ['grupos' => ['1', '2']],
            'Teoría General del Proceso' => ['grupos' => ['1', '2']],
            'Derecho Constitucional I' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Derecho de Bienes' => ['grupos' => ['1', '2']],
            'Derecho de Obligaciones' => ['grupos' => ['1', '2']],
            'Derecho Penal I' => ['grupos' => ['1', '2']],
            'Derecho Constitucional II' => ['grupos' => ['1', '2']],
            'Derecho de Sucesiones' => ['grupos' => ['1', '2']],
            'Contratos Civiles' => ['grupos' => ['1', '2']],
            'Derecho Penal II' => ['grupos' => ['1', '2']],
            'Derecho Administrativo I' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Derecho Procesal Civil I' => ['grupos' => ['1', '2']],
            'Derecho Mercantil I' => ['grupos' => ['1', '2']],
            'Derecho Laboral' => ['grupos' => ['1', '2']],
            'Derecho Administrativo II' => ['grupos' => ['1', '2']],
            'Derecho Procesal Civil II' => ['grupos' => ['1', '2']],
            'Derecho Mercantil II' => ['grupos' => ['1', '2']],
            'Derecho Procesal Penal' => ['grupos' => ['1', '2']],
            'Derecho Tributario' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Derecho Notarial y Registral I' => ['grupos' => ['1', '2']],
            'Derecho Internacional Público' => ['grupos' => ['1', '2']],
            'Medicina Forense' => ['grupos' => ['1', '2']],
            'Derecho Ambiental' => ['grupos' => ['1', '2']],
            'Derecho Notarial y Registral II' => ['grupos' => ['1', '2']],
            'Derecho Internacional Privado' => ['grupos' => ['1', '2']],
            'Criminología' => ['grupos' => ['1', '2']],
            'Métodos Alternos de Resolución de Conflictos' => ['grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            'Prácticas Penales y Civiles' => ['grupos' => ['1', '2']],
            'Filosofía del Derecho' => ['grupos' => ['1', '2']],
            'Técnicas de Litigación Oral' => ['grupos' => ['1', '2']],
            'Taller de Tesis' => ['grupos' => ['1', '2']],
            'Prácticas de Familia, Laboral y Administrativo' => ['grupos' => ['1', '2']],
            'Deontología Jurídica' => ['grupos' => ['1', '2']],
        ],
    ],
    'Diplomacia y Relaciones Internacionales' => [
        'Primer Año' => [
            'Introducción a las Relaciones Internacionales' => ['grupos' => ['1', '2']],
            'Historia Universal' => ['grupos' => ['1', '2']],
            'Teoría de Relaciones Internacionales I' => ['grupos' => ['1', '2']],
            'Derecho Constitucional' => ['grupos' => ['1', '2']],
            'Introducción al Estudio del Derecho' => ['grupos' => ['1', '2']],
            'Geopolítica' => ['grupos' => ['1', '2']],
            'Técnicas de Redacción' => ['grupos' => ['1', '2']],
            'Historia de Nicaragua' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Teoría de Relaciones Internacionales II' => ['grupos' => ['1', '2']],
            'Economía Internacional' => ['grupos' => ['1', '2']],
            'Derecho Internacional Público' => ['grupos' => ['1', '2']],
            'Organismos Internacionales I' => ['grupos' => ['1', '2']],
            'Política Exterior I' => ['grupos' => ['1', '2']],
            'Protocolo y Ceremonial Diplomático' => ['grupos' => ['1', '2']],
            'Análisis de Política Internacional' => ['grupos' => ['1', '2']],
            'Resolución de Conflictos' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Cooperación Internacional' => ['grupos' => ['1', '2']],
            'Derechos Humanos' => ['grupos' => ['1', '2']],
            'Política Exterior de Nicaragua' => ['grupos' => ['1', '2']],
            'Organismos Internacionales II' => ['grupos' => ['1', '2']],
            'Integración Regional' => ['grupos' => ['1', '2']],
            'Seguridad Internacional' => ['grupos' => ['1', '2']],
            'Negociación y Mediación' => ['grupos' => ['1', '2']],
            'Opinión Pública Internacional' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Derecho Diplomático y Consular' => ['grupos' => ['1', '2']],
            'Análisis de Coyuntura' => ['grupos' => ['1', '2']],
            'Política Exterior de EE.UU.' => ['grupos' => ['1', '2']],
            'Taller de Investigación Diplomática' => ['grupos' => ['1', '2']],
            'Prácticas Profesionales' => ['grupos' => ['1', '2']],
            'Seminario de Graduación' => ['grupos' => ['1', '2']],
        ],
    ],
    'Medicina' => [
        'Primer Año' => [
            'Anatomía Humana I' => ['grupos' => ['1', '2']],
            'Histología y Embriología I' => ['grupos' => ['1', '2']],
            'Bioquímica' => ['grupos' => ['1', '2']],
            'Salud Pública I' => ['grupos' => ['1', '2']],
            'Anatomía Humana II' => ['grupos' => ['1', '2']],
            'Histología y Embriología II' => ['grupos' => ['1', '2']],
            'Fisiología Médica I' => ['grupos' => ['1', '2']],
            'Introducción a la Medicina' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Microbiología Médica' => ['grupos' => ['1', '2']],
            'Parasitología Médica' => ['grupos' => ['1', '2']],
            'Fisiología Médica II' => ['grupos' => ['1', '2']],
            'Patología General' => ['grupos' => ['1', '2']],
            'Farmacología Médica I' => ['grupos' => ['1', '2']],
            'Inmunología Médica' => ['grupos' => ['1', '2']],
            'Semiología Médica I' => ['grupos' => ['1', '2']],
            'Epidemiología' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Medicina Interna I' => ['grupos' => ['1', '2']],
            'Cirugía I' => ['grupos' => ['1', '2']],
            'Ginecología y Obstetricia I' => ['grupos' => ['1', '2']],
            'Pediatría I' => ['grupos' => ['1', '2']],
            'Psiquiatría' => ['grupos' => ['1', '2']],
            'Radiología e Imagen' => ['grupos' => ['1', '2']],
            'Medicina Legal' => ['grupos' => ['1', '2']],
            'Farmacología Médica II' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Medicina Interna II' => ['grupos' => ['1', '2']],
            'Cirugía II' => ['grupos' => ['1', '2']],
            'Ginecología y Obstetricia II' => ['grupos' => ['1', '2']],
            'Pediatría II' => ['grupos' => ['1', '2']],
            'Dermatología' => ['grupos' => ['1', '2']],
            'Oftalmología' => ['grupos' => ['1', '2']],
            'Otorrinolaringología' => ['grupos' => ['1', '2']],
            'Urología' => ['grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            'Internado Rotatorio en Medicina Interna' => ['grupos' => ['1', '2']],
            'Internado Rotatorio en Cirugía' => ['grupos' => ['1', '2']],
            'Internado Rotatorio en Pediatría' => ['grupos' => ['1', '2']],
            'Internado Rotatorio en Ginecología y Obstetricia' => ['grupos' => ['1', '2']],
        ],
    ],
    'Psicología' => [
        'Primer Año' => [
            'Historia de la Psicología' => ['grupos' => ['1', '2']],
            'Procesos Psicológicos I' => ['grupos' => ['1', '2']],
            'Bases Biológicas del Comportamiento' => ['grupos' => ['1', '2']],
            'Estadística Descriptiva' => ['grupos' => ['1', '2']],
            'Procesos Psicológicos II' => ['grupos' => ['1', '2']],
            'Psicología del Desarrollo I' => ['grupos' => ['1', '2']],
            'Teorías de la Personalidad' => ['grupos' => ['1', '2']],
            'Psicometría' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Psicología Social' => ['grupos' => ['1', '2']],
            'Psicopatología I' => ['grupos' => ['1', '2']],
            'Psicología del Desarrollo II' => ['grupos' => ['1', '2']],
            'Neuropsicología' => ['grupos' => ['1', '2']],
            'Psicopatología II' => ['grupos' => ['1', '2']],
            'Psicología Educativa' => ['grupos' => ['1', '2']],
            'Evaluación Psicológica I' => ['grupos' => ['1', '2']],
            'Psicología Organizacional' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Psicología Clínica I' => ['grupos' => ['1', '2']],
            'Teorías del Aprendizaje' => ['grupos' => ['1', '2']],
            'Psicología Comunitaria' => ['grupos' => ['1', '2']],
            'Diseños de Investigación' => ['grupos' => ['1', '2']],
            'Psicología Clínica II' => ['grupos' => ['1', '2']],
            'Técnicas de Entrevista' => ['grupos' => ['1', '2']],
            'Evaluación Psicológica II' => ['grupos' => ['1', '2']],
            'Psicofarmacología' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Psicoterapia I (Psicoanálisis)' => ['grupos' => ['1', '2']],
            'Orientación Vocacional y Profesional' => ['grupos' => ['1', '2']],
            'Psicología de la Salud' => ['grupos' => ['1', '2']],
            'Taller de Tesis I' => ['grupos' => ['1', '2']],
            'Psicoterapia II (Cognitivo-Conductual)' => ['grupos' => ['1', '2']],
            'Psicología Forense' => ['grupos' => ['1', '2']],
            'Intervención en Crisis' => ['grupos' => ['1', '2']],
            'Ética Profesional' => ['grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            'Prácticas Profesionales Supervisadas' => ['grupos' => ['1', '2']],
            'Taller de Tesis II' => ['grupos' => ['1', '2']],
            'Examen de Grado' => ['grupos' => ['1', '2']],
        ],
    ],
    'Nutrición' => [
        'Primer Año' => [
            'Química General y Orgánica' => ['grupos' => ['1', '2']],
            'Biología Celular' => ['grupos' => ['1', '2']],
            'Anatomía Humana' => ['grupos' => ['1', '2']],
            'Fundamentos de Nutrición' => ['grupos' => ['1', '2']],
            'Bioquímica de la Nutrición' => ['grupos' => ['1', '2']],
            'Fisiología Humana' => ['grupos' => ['1', '2']],
            'Microbiología de Alimentos' => ['grupos' => ['1', '2']],
            'Evaluación del Estado Nutricional' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Nutrición en el Ciclo de Vida' => ['grupos' => ['1', '2']],
            'Tecnología de Alimentos' => ['grupos' => ['1', '2']],
            'Dietética' => ['grupos' => ['1', '2']],
            'Salud Pública y Epidemiología' => ['grupos' => ['1', '2']],
            'Fisiopatología' => ['grupos' => ['1', '2']],
            'Nutrición Clínica I' => ['grupos' => ['1', '2']],
            'Bioestadística' => ['grupos' => ['1', '2']],
            'Educación Nutricional' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Nutrición Clínica II' => ['grupos' => ['1', '2']],
            'Bioquímica Clínica' => ['grupos' => ['1', '2']],
            'Soporte Nutricional' => ['grupos' => ['1', '2']],
            'Psicología de la Alimentación' => ['grupos' => ['1', '2']],
            'Nutrición Deportiva' => ['grupos' => ['1', '2']],
            'Gestión de Servicios de Alimentación' => ['grupos' => ['1', '2']],
            'Investigación en Nutrición' => ['grupos' => ['1', '2']],
            'Farmacología en Nutrición' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Prácticas Comunitarias' => ['grupos' => ['1', '2']],
            'Prácticas Clínicas' => ['grupos' => ['1', '2']],
            'Seminario de Tesis' => ['grupos' => ['1', '2']],
        ],
    ],
    'Odontología' => [
        'Primer Año' => [
            'Anatomía Humana y de Cabeza y Cuello' => ['grupos' => ['1', '2']],
            'Histología y Embriología General y Dental' => ['grupos' => ['1', '2']],
            'Bioquímica' => ['grupos' => ['1', '2']],
            'Materiales Dentales I' => ['grupos' => ['1', '2']],
            'Fisiología General y Oral' => ['grupos' => ['1', '2']],
            'Microbiología e Inmunología' => ['grupos' => ['1', '2']],
            'Operatoria Dental I' => ['grupos' => ['1', '2']],
            'Radiología Oral I' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Patología General y Oral' => ['grupos' => ['1', '2']],
            'Farmacología' => ['grupos' => ['1', '2']],
            'Anestesia y Exodoncia I' => ['grupos' => ['1', '2']],
            'Operatoria Dental II' => ['grupos' => ['1', '2']],
            'Periodoncia I' => ['grupos' => ['1', '2']],
            'Prostodoncia Fija y Removible I' => ['grupos' => ['1', '2']],
            'Endodoncia I' => ['grupos' => ['1', '2']],
            'Salud Pública Dental' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Clínica de Operatoria Dental I' => ['grupos' => ['1', '2']],
            'Clínica de Periodoncia I' => ['grupos' => ['1', '2']],
            'Clínica de Endodoncia I' => ['grupos' => ['1', '2']],
            'Odontopediatría I' => ['grupos' => ['1', '2']],
            'Ortodoncia Preventiva e Interceptiva' => ['grupos' => ['1', '2']],
            'Cirugía Bucal I' => ['grupos' => ['1', '2']],
            'Medicina Interna para Odontólogos' => ['grupos' => ['1', '2']],
            'Oclusión' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Clínica Integral del Adulto I' => ['grupos' => ['1', '2']],
            'Clínica Integral del Niño I' => ['grupos' => ['1', '2']],
            'Cirugía Bucal II' => ['grupos' => ['1', '2']],
            'Implantología Oral' => ['grupos' => ['1', '2']],
            'Odontología Legal y Forense' => ['grupos' => ['1', '2']],
            'Prótesis Total y Parcial' => ['grupos' => ['1', '2']],
            'Patología Bucal' => ['grupos' => ['1', '2']],
            'Taller de Investigación' => ['grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            'Clínica Integral del Adulto II' => ['grupos' => ['1', '2']],
            'Clínica Integral del Niño II' => ['grupos' => ['1', '2']],
            'Pasantías Hospitalarias' => ['grupos' => ['1', '2']],
            'Administración de Consultorio Dental' => ['grupos' => ['1', '2']],
            'Tesis de Grado' => ['grupos' => ['1', '2']],
        ],
    ],
    'Arquitectura' => [
        'Primer Año' => [
            'Geometría Descriptiva' => ['grupos' => ['1', '2']],
            'Dibujo Arquitectónico I' => ['grupos' => ['1', '2']],
            'Taller de Diseño I' => ['grupos' => ['1', '2']],
            'Matemáticas para Arquitectura' => ['grupos' => ['1', '2']],
            'Historia del Arte y la Arquitectura I' => ['grupos' => ['1', '2']],
            'Dibujo Arquitectónico II' => ['grupos' => ['1', '2']],
            'Taller de Diseño II' => ['grupos' => ['1', '2']],
            'Física Aplicada' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Taller de Diseño III' => ['grupos' => ['1', '2']],
            'Estructuras I' => ['grupos' => ['1', '2']],
            'Historia de la Arquitectura II' => ['grupos' => ['1', '2']],
            'Sistemas Constructivos I' => ['grupos' => ['1', '2']],
            'Taller de Diseño IV' => ['grupos' => ['1', '2']],
            'Estructuras II' => ['grupos' => ['1', '2']],
            'Instalaciones I (Hidrosanitarias)' => ['grupos' => ['1', '2']],
            'Sistemas Constructivos II' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Taller de Diseño V (Vivienda)' => ['grupos' => ['1', '2']],
            'Urbanismo I' => ['grupos' => ['1', '2']],
            'Instalaciones II (Eléctricas y Especiales)' => ['grupos' => ['1', '2']],
            'Arquitectura Bioclimática' => ['grupos' => ['1', '2']],
            'Taller de Diseño VI (Comercial)' => ['grupos' => ['1', '2']],
            'Urbanismo II' => ['grupos' => ['1', '2']],
            'Administración de Proyectos de Construcción' => ['grupos' => ['1', '2']],
            'Presupuestos de Construcción' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Taller de Diseño VII (Institucional)' => ['grupos' => ['1', '2']],
            'Paisajismo' => ['grupos' => ['1', '2']],
            'Restauración de Monumentos' => ['grupos' => ['1', '2']],
            'Diseño Estructural en Acero y Concreto' => ['grupos' => ['1', '2']],
            'Taller de Diseño VIII (Urbano)' => ['grupos' => ['1', '2']],
            'Legislación de la Construcción' => ['grupos' => ['1', '2']],
            'Taller de Tesis I' => ['grupos' => ['1', '2']],
            'Prácticas Profesionales' => ['grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            'Taller de Tesis II' => ['grupos' => ['1', '2']],
            'Gestión Inmobiliaria' => ['grupos' => ['1', '2']],
            'Seminario de Arquitectura Contemporánea' => ['grupos' => ['1', '2']],
            'Proyecto de Graduación' => ['grupos' => ['1', '2']],
        ],
    ],
    'Ingeniería Civil' => [
        'Primer Año' => [
            'Cálculo I' => ['grupos' => ['1', '2']],
            'Física I' => ['grupos' => ['1', '2']],
            'Química General' => ['grupos' => ['1', '2']],
            'Dibujo Técnico' => ['grupos' => ['1', '2']],
            'Introducción a la Ingeniería Civil' => ['grupos' => ['1', '2']],
            'Cálculo II' => ['grupos' => ['1', '2']],
            'Física II' => ['grupos' => ['1', '2']],
            'Estática' => ['grupos' => ['1', '2']],
            'Programación para Ingenieros' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Cálculo III' => ['grupos' => ['1', '2']],
            'Dinámica' => ['grupos' => ['1', '2']],
            'Mecánica de Materiales I' => ['grupos' => ['1', '2']],
            'Topografía' => ['grupos' => ['1', '2']],
            'Geología para Ingenieros' => ['grupos' => ['1', '2']],
            'Ecuaciones Diferenciales' => ['grupos' => ['1', '2']],
            'Mecánica de Materiales II' => ['grupos' => ['1', '2']],
            'Mecánica de Fluidos' => ['grupos' => ['1', '2']],
            'Materiales de Construcción' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Análisis Estructural I' => ['grupos' => ['1', '2']],
            'Hidrología' => ['grupos' => ['1', '2']],
            'Mecánica de Suelos I' => ['grupos' => ['1', '2']],
            'Ingeniería de Tránsito' => ['grupos' => ['1', '2']],
            'Análisis Estructural II' => ['grupos' => ['1', '2']],
            'Hidráulica' => ['grupos' => ['1', '2']],
            'Mecánica de Suelos II' => ['grupos' => ['1', '2']],
            'Diseño de Pavimentos' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Diseño de Estructuras de Concreto Reforzado I' => ['grupos' => ['1', '2']],
            'Ingeniería Sanitaria' => ['grupos' => ['1', '2']],
            'Cimentaciones' => ['grupos' => ['1', '2']],
            'Ingeniería de Costos y Presupuestos' => ['grupos' => ['1', '2']],
            'Diseño de Estructuras de Concreto Reforzado II' => ['grupos' => ['1', '2']],
            'Abastecimiento de Agua Potable' => ['grupos' => ['1', '2']],
            'Ingeniería de Puentes' => ['grupos' => ['1', '2']],
            'Administración de la Construcción' => ['grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            'Diseño de Estructuras de Acero' => ['grupos' => ['1', '2']],
            'Ingeniería Sísmica' => ['grupos' => ['1', '2']],
            'Taller de Diseño Estructural' => ['grupos' => ['1', '2']],
            'Ética y Práctica Profesional' => ['grupos' => ['1', '2']],
            'Proyecto de Graduación' => ['grupos' => ['1', '2']],
            'Prácticas Profesionales' => ['grupos' => ['1', '2']],
        ],
    ],
    'Ingeniería Industrial' => [
        'Primer Año' => [
            'Cálculo I' => ['grupos' => ['1', '2']],
            'Física I' => ['grupos' => ['1', '2']],
            'Química General' => ['grupos' => ['1', '2']],
            'Dibujo Industrial' => ['grupos' => ['1', '2']],
            'Introducción a la Ingeniería Industrial' => ['grupos' => ['1', '2']],
            'Cálculo II' => ['grupos' => ['1', '2']],
            'Física II' => ['grupos' => ['1', '2']],
            'Electricidad y Magnetismo' => ['grupos' => ['1', '2']],
            'Estadística I' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Procesos de Manufactura' => ['grupos' => ['1', '2']],
            'Ingeniería de Métodos' => ['grupos' => ['1', '2']],
            'Contabilidad de Costos' => ['grupos' => ['1', '2']],
            'Investigación de Operaciones I' => ['grupos' => ['1', '2']],
            'Termodinámica' => ['grupos' => ['1', '2']],
            'Ingeniería Económica' => ['grupos' => ['1', '2']],
            'Seguridad e Higiene Industrial' => ['grupos' => ['1', '2']],
            'Control Estadístico de Calidad' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Investigación de Operaciones II' => ['grupos' => ['1', '2']],
            'Gestión de la Calidad Total' => ['grupos' => ['1', '2']],
            'Planeación y Control de la Producción I' => ['grupos' => ['1', '2']],
            'Diseño de Instalaciones' => ['grupos' => ['1', '2']],
            'Ergonomía' => ['grupos' => ['1', '2']],
            'Logística y Cadena de Suministro' => ['grupos' => ['1', '2']],
            'Planeación y Control de la Producción II' => ['grupos' => ['1', '2']],
            'Automatización Industrial' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Simulación de Sistemas' => ['grupos' => ['1', '2']],
            'Formulación y Evaluación de Proyectos' => ['grupos' => ['1', '2']],
            'Gestión del Mantenimiento' => ['grupos' => ['1', '2']],
            'Sistemas Integrados de Gestión (ISO)' => ['grupos' => ['1', '2']],
            'Ingeniería Financiera' => ['grupos' => ['1', '2']],
            'Gestión Ambiental' => ['grupos' => ['1', '2']],
            'Marketing para Ingenieros' => ['grupos' => ['1', '2']],
            'Taller de Tesis' => ['grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            'Prácticas Profesionales' => ['grupos' => ['1', '2']],
            'Proyecto de Grado' => ['grupos' => ['1', '2']],
        ],
    ],
    'Ingeniería en Sistemas de Información' => [
        'Primer Año' => [
            'Cálculo I' => ['grupos' => ['1', '2']],
            'Física I' => ['grupos' => ['1', '2']],
            'Introducción a la Programación' => ['grupos' => ['1', '2']],
            'Comunicación Oral y Escrita' => ['grupos' => ['1', '2']],
            'Cálculo II' => ['grupos' => ['1', '2']],
            'Física II' => ['grupos' => ['1', '2']],
            'Programación I' => ['grupos' => ['1', '2']],
            'Álgebra Lineal' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Cálculo III' => ['grupos' => ['1', '2']],
            'Programación II' => ['grupos' => ['1', '2']],
            'Contabilidad de Costos' => ['grupos' => ['1', '2']],
            'Estructuras Discretas' => ['grupos' => ['1', '2']],
            'Ecuaciones Diferenciales' => ['grupos' => ['1', '2']],
            'Programación Orientada a Objetos' => ['grupos' => ['1', '2']],
            'Base de Datos I' => ['grupos' => ['1', '2']],
            'Análisis y Diseño de Sistemas' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Probabilidad y Estadística' => ['grupos' => ['1', '2']],
            'Base de Datos II' => ['grupos' => ['1', '2']],
            'Sistemas Operativos' => ['grupos' => ['1', '2']],
            'Redes de Computadoras I' => ['grupos' => ['1', '2']],
            'Investigación de Operaciones' => ['grupos' => ['1', '2']],
            'Ingeniería de Software I' => ['grupos' => ['1', '2']],
            'Redes de Computadoras II' => ['grupos' => ['1', '2']],
            'Programación Web' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Inteligencia Artificial' => ['grupos' => ['1', '2']],
            'Seguridad Informática' => ['grupos' => ['1', '2']],
            'Ingeniería de Software II' => ['grupos' => ['1', '2']],
            'Redes Avanzadas' => ['grupos' => ['1', '2']],
            'Sistemas de Información Gerencial' => ['grupos' => ['1', '2']],
            'Auditoría de Sistemas' => ['grupos' => ['1', '2']],
            'Taller de Graduación I' => ['grupos' => ['1', '2']],
        ],
        'Quinto Año' => [
            'Prácticas Profesionales' => ['grupos' => ['1', '2']],
            'Taller de Graduación II' => ['grupos' => ['1', '2']],
            'Computación en la Nube' => ['grupos' => ['1', '2']],
            'Desarrollo de Aplicaciones Móviles' => ['grupos' => ['1', '2']],
        ],
    ],
    'Marketing y Publicidad' => [
        'Primer Año' => [
            'Principios de Marketing' => ['grupos' => ['1', '2']],
            'Comportamiento del Consumidor' => ['grupos' => ['1', '2']],
            'Comunicación Integrada' => ['grupos' => ['1', '2']],
            'Diseño Gráfico Publicitario' => ['grupos' => ['1', '2']],
            'Fundamentos de Economía' => ['grupos' => ['1', '2']],
            'Fotografía Publicitaria' => ['grupos' => ['1', '2']],
            'Costos y Presupuestos' => ['grupos' => ['1', '2']],
            'Investigación de Mercados I' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Estrategia de Marca (Branding)' => ['grupos' => ['1', '2']],
            'Marketing Digital I' => ['grupos' => ['1', '2']],
            'Planificación de Medios' => ['grupos' => ['1', '2']],
            'Redacción Creativa' => ['grupos' => ['1', '2']],
            'Derecho Publicitario' => ['grupos' => ['1', '2']],
            'Marketing Digital II (SEO/SEM)' => ['grupos' => ['1', '2']],
            'Producción Audiovisual' => ['grupos' => ['1', '2']],
            'Relaciones Públicas' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Gerencia de Producto' => ['grupos' => ['1', '2']],
            'E-Commerce' => ['grupos' => ['1', '2']],
            'Psicología Publicitaria' => ['grupos' => ['1', '2']],
            'Marketing Estratégico' => ['grupos' => ['1', '2']],
            'Neuromarketing' => ['grupos' => ['1', '2']],
            'Análisis de Datos (Analytics)' => ['grupos' => ['1', '2']],
            'Publicidad Exterior y BTL' => ['grupos' => ['1', '2']],
            'Taller de Campañas Publicitarias' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Marketing de Servicios' => ['grupos' => ['1', '2']],
            'Gerencia de Ventas' => ['grupos' => ['1', '2']],
            'Ética y Responsabilidad Social' => ['grupos' => ['1', '2']],
            'Seminario de Tesis' => ['grupos' => ['1', '2']],
            'Prácticas Profesionales' => ['grupos' => ['1', '2']],
        ],
    ],
    'Diseño y Comunicación Visual' => [
        'Primer Año' => [
            'Fundamentos del Diseño' => ['grupos' => ['1', '2']],
            'Teoría del Color' => ['grupos' => ['1', '2']],
            'Dibujo Artístico I' => ['grupos' => ['1', '2']],
            'Historia del Arte' => ['grupos' => ['1', '2']],
            'Tipografía I' => ['grupos' => ['1', '2']],
            'Dibujo Artístico II' => ['grupos' => ['1', '2']],
            'Fotografía Básica' => ['grupos' => ['1', '2']],
            'Geometría del Diseño' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Diseño Editorial' => ['grupos' => ['1', '2']],
            'Ilustración Digital' => ['grupos' => ['1', '2']],
            'Tipografía II' => ['grupos' => ['1', '2']],
            'Historia del Diseño Gráfico' => ['grupos' => ['1', '2']],
            'Diseño de Empaques (Packaging)' => ['grupos' => ['1', '2']],
            'Modelado 3D' => ['grupos' => ['1', '2']],
            'Diseño Web I' => ['grupos' => ['1', '2']],
            'Semiótica Visual' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Diseño de Identidad Corporativa (Branding)' => ['grupos' => ['1', '2']],
            'Animación 2D' => ['grupos' => ['1', '2']],
            'Diseño de Interfaz de Usuario (UI)' => ['grupos' => ['1', '2']],
            'Producción Gráfica' => ['grupos' => ['1', '2']],
            'Diseño de Experiencia de Usuario (UX)' => ['grupos' => ['1', '2']],
            'Dirección de Arte' => ['grupos' => ['1', '2']],
            'Portafolio Profesional I' => ['grupos' => ['1', '2']],
            'Diseño Web II' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Diseño de Información (Infografía)' => ['grupos' => ['1', '2']],
            'Motion Graphics' => ['grupos' => ['1', '2']],
            'Portafolio Profesional II' => ['grupos' => ['1', '2']],
            'Gestión de Proyectos de Diseño' => ['grupos' => ['1', '2']],
            'Prácticas Profesionales' => ['grupos' => ['1', '2']],
            'Proyecto de Tesis' => ['grupos' => ['1', '2']],
        ],
    ],
    'Comunicación y Relaciones Públicas' => [
        'Primer Año' => [
            'Teoría de la Comunicación' => ['grupos' => ['1', '2']],
            'Redacción Periodística I' => ['grupos' => ['1', '2']],
            'Comunicación Oral' => ['grupos' => ['1', '2']],
            'Historia de los Medios' => ['grupos' => ['1', '2']],
            'Introducción a las Relaciones Públicas' => ['grupos' => ['1', '2']],
            'Redacción Periodística II' => ['grupos' => ['1', '2']],
            'Opinión Pública' => ['grupos' => ['1', '2']],
            'Fotoperiodismo' => ['grupos' => ['1', '2']],
        ],
        'Segundo Año' => [
            'Comunicación Corporativa' => ['grupos' => ['1', '2']],
            'Gestión de Crisis' => ['grupos' => ['1', '2']],
            'Producción Radiofónica' => ['grupos' => ['1', '2']],
            'Ética y Legislación de Medios' => ['grupos' => ['1', '2']],
            'Organización de Eventos' => ['grupos' => ['1', '2']],
            'Comunicación Digital y Redes Sociales' => ['grupos' => ['1', '2']],
            'Taller de Televisión' => ['grupos' => ['1', '2']],
            'Estrategias de Relaciones Públicas' => ['grupos' => ['1', '2']],
        ],
        'Tercer Año' => [
            'Comunicación Política y Lobbying' => ['grupos' => ['1', '2']],
            'Comunicación Interna' => ['grupos' => ['1', '2']],
            'Investigación de la Comunicación' => ['grupos' => ['1', '2']],
            'Producción de Contenidos Digitales' => ['grupos' => ['1', '2']],
            'Protocolo Empresarial y Social' => ['grupos' => ['1', '2']],
            'Gestión de la Reputación Online' => ['grupos' => ['1', '2']],
            'Portavocía' => ['grupos' => ['1', '2']],
            'Taller de Agencia' => ['grupos' => ['1', '2']],
        ],
        'Cuarto Año' => [
            'Comunicación Intercultural' => ['grupos' => ['1', '2']],
            'Responsabilidad Social Corporativa' => ['grupos' => ['1', '2']],
            'Seminario de Tesis' => ['grupos' => ['1', '2']],
            'Prácticas Profesionales' => ['grupos' => ['1', '2']],
        ],
    ],
];